#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:~/bin:$PATH

start=$(date "+%s")
<<COMMENT
  Variable
COMMENT
# Quefei Core 的版本
version=':~1.0'

<<COMMENT
  Function
COMMENT
# echo 颜色
colorText()
{
	echo -e "\e[0;$2m$1\e[0m"
}

echoRed()
{
	echo $(colorText "$1" "31")
}

echoGreen()
{
	echo $(colorText "$1" "32")
}

echoYellow()
{
	echo $(colorText "$1" "33")
}

echoBlue()
{
	echo $(colorText "$1" "34")
}

# read 颜色
readRed()
{
	echo -n $(colorText "$1" "31")
	read $2
}

readGreen()
{
	echo -n $(colorText "$1" "32")
	read $2
}

readYellow()
{
	echo -n $(colorText "$1" "33")
	read $2
}

readBlue()
{
	echo -n $(colorText "$1" "34")
	read $2
}

<<COMMENT
  Main
COMMENT
# 检查当前用户是否为 root
if [ $(id -u) != '0' ]; then
	echoRed 'Error: You have to be root to run this script'
	exit 1
fi

# 检查当前目录是否为 Laravel 的根目录
if ([ -f $(pwd)/composer.json ] && [ -f $(pwd)/artisan ] &&
	[ -d $(pwd)/app ] && [ -d $(pwd)/database ] &&
	[ -d $(pwd)/public ] && [ -d $(pwd)/resources ] &&
	[ -d $(pwd)/config ] && [ -d $(pwd)/routes ] &&
	[ -d $(pwd)/vendor ]); then
	
	:
else
	echoRed 'Error: You have to go to the laravel root directory'
	exit 2
fi

# 排除错误1
grep 'minimum-stability' composer.json &> /dev/null || sed -i '/^ *"name"/a\    "minimum-stability": "dev",' composer.json || exit 20
grep 'CACHE_DRIVER=array' .env &> /dev/null || (sed -i "/CACHE_DRIVER/d" .env; echo "CACHE_DRIVER=array" >> .env) || exit 44

# 安装
grep 'quefei/core' vendor/composer/installed.json &> /dev/null || composer require quefei/core$version || exit 21

# 注册
aliyunmns='Quefei\\AliyunMns\\Providers\\AliyunMnsServiceProvider::class,'
aliyundm='Quefei\\AliyunDm\\Providers\\AliyunDmServiceProvider::class,'
myauth='Quefei\\Myauth\\Providers\\MyauthServiceProvider::class,'
myentrust='Quefei\\Myentrust\\Providers\\MyentrustServiceProvider::class,'
core='Quefei\\Core\\Providers\\CoreServiceProvider::class,'
entrust='Zizaco\\Entrust\\EntrustServiceProvider::class,'
html='Collective\\Html\\HtmlServiceProvider::class,'
searchy='TomLingham\\Searchy\\SearchyServiceProvider::class,'

MNS="'MNS'=>Quefei\\\\AliyunMns\\\\Facades\\\\MNS::class,"
DM="'DM'=>Quefei\\\\AliyunDm\\\\Facades\\\\DM::class,"
Entrust="'Entrust'=>Zizaco\\\\Entrust\\\\EntrustFacade::class,"
Form="'Form'=>Collective\\\\Html\\\\FormFacade::class,"
Html="'Html'=>Collective\\\\Html\\\\HtmlFacade::class,"
Searchy="'Searchy'=>TomLingham\\\\Searchy\\\\Facades\\\\Searchy::class,"

for providers in $aliyunmns $aliyundm $myauth $myentrust $core $entrust $html $searchy
do
	grep $providers config/app.php &> /dev/null || sed -i "/^ *'providers'/a\        $providers" config/app.php || exit 22
done

for aliases in $MNS $DM $Entrust $Form $Html $Searchy
do
	myaliases=$(echo $aliases | awk -F\> '{ print $2 }')
	grep $myaliases config/app.php &> /dev/null || sed -i "/^ *'aliases'/a\        $aliases" config/app.php || exit 23
done

# 生成配置文件
php artisan vendor:publish || exit 24

# 配置 Auth
grep "'table' *=> *'users'," config/auth.php | grep -v '/' &> /dev/null || sed -i "/User::class,/a\            'table' => 'users'," config/auth.php || exit 25

# 注册中间件
myadmin="'myadmin'=>\\\\Quefei\\\\Myentrust\\\\Middleware\\\\Myadmin::class,"
myrole="'myrole'=>\\\\Quefei\\\\Myentrust\\\\Middleware\\\\Myrole::class,"
mypermission="'mypermission'=>\\\\Quefei\\\\Myentrust\\\\Middleware\\\\Mypermission::class,"
myuser="'myuser'=>\\\\Quefei\\\\Myentrust\\\\Middleware\\\\Myuser::class,"
role="'role'=>\\\\Zizaco\\\\Entrust\\\\Middleware\\\\EntrustRole::class,"
permission="'permission'=>\\\\Zizaco\\\\Entrust\\\\Middleware\\\\EntrustPermission::class,"
ability="'ability'=>\\\\Zizaco\\\\Entrust\\\\Middleware\\\\EntrustAbility::class,"

for routeMiddleware in $myadmin $myrole $mypermission $myuser $role $permission $ability
do
	myRouteMiddleware=$(echo $routeMiddleware | awk -F\> '{ print $2 }')
	grep $myRouteMiddleware app/Http/Kernel.php &> /dev/null || sed -i "/protected.*routeMiddleware/a\        $routeMiddleware" app/Http/Kernel.php || exit 26
done

# 生成 Core 所需文件

a=0; b=0; c=0

while ((a<10))
do
	readYellow "Site Title: " title
	
	if [ "${title}" = "" ]; then
		title=$(cat vendor/quefei/core/src/Console/buffer/title.buffer)
		break
    fi
	
	for titleFile in 'vendor/quefei/myauth/src/Console/stubs/make/views/welcome.stub' \
					 'vendor/quefei/myauth/src/Console/stubs/make/views/home.stub' \
					 'vendor/quefei/myauth/src/Console/stubs/make/views/layouts/app.stub' \
					 'vendor/quefei/myauth/src/Console/stubs/make/views/auth/register.stub' \
					 'vendor/quefei/myauth/src/Console/stubs/make/views/auth/emailRegister.stub' \
					 'vendor/quefei/myauth/src/Console/stubs/make/views/auth/login.stub' \
					 'vendor/quefei/myauth/src/Console/stubs/make/views/auth/activate/activate.stub' \
					 'vendor/quefei/myauth/src/Console/stubs/make/views/auth/activate/activateFail.stub' \
					 'vendor/quefei/myauth/src/Console/stubs/make/views/auth/activate/activateSuccess.stub' \
					 'vendor/quefei/myentrust/src/Views/role/index.blade.php' \
					 'vendor/quefei/myentrust/src/Views/user/index.blade.php' \
					 'vendor/quefei/myentrust/src/Views/searchUser/index.blade.php'
	do
		if (grep $title $titleFile &> /dev/null); then
			echoRed 'Error: You have to change site title'
			((a++))
			break 1
		else
			break 2
		fi
	done
done

((a==10)) && exit 45

while ((b<10))
do
	readYellow "Site Logo: " logo
	
	if [ "${logo}" = "" ]; then
		logo=$(cat vendor/quefei/core/src/Console/buffer/logo.buffer)
		break
    fi
	
	for logoFile in 'vendor/quefei/myauth/src/Console/stubs/make/views/layouts/_nav.stub'
	do
		if (grep $logo $logoFile &> /dev/null); then
			echoRed 'Error: You have to change site logo'
			((b++))
			break 1
		else
			break 2
		fi
	done
done

((b==10)) && exit 46

while ((c<10))
do
	readYellow "Site Copyright: " copyright
	
	if [ "${copyright}" = "" ]; then
		copyright=$(cat vendor/quefei/core/src/Console/buffer/copyright.buffer)
		break
    fi
	
	for copyrightFile in 'vendor/quefei/myauth/src/Console/stubs/make/views/layouts/_footer.stub'
	do
		if (grep $copyright $copyrightFile &> /dev/null); then
			echoRed 'Error: You have to change site copyright'
			((c++))
			break 1
		else
			break 2
		fi
	done
done

((c==10)) && exit 47

php artisan make:core --title=$title --logo=$logo --copyright=$copyright | grep 'Error' && exit 27

# 生成 Myauth 所需文件
php artisan make:myauth --force || exit 28

# 生成 Myentrust 所需文件

[ -f database/seeds/EntrustTableSeeder.php ] || php artisan make:seeder EntrustTableSeeder || exit 29

if (find database/migrations -name "*entrust_setup_tables.php" | grep 'entrust_setup_tables.php' &> /dev/null); then
	:
else
	echo 'yes' | php artisan entrust:migration || exit 30
fi

php artisan make:myentrust --force || exit 31

# 运行迁移
if (php artisan migrate:status | grep 'No migrations found' &> /dev/null) || (php artisan migrate:status | grep '^| *N' &> /dev/null); then
	if (grep 'DB_CONNECTION=..' .env &&
		grep 'DB_HOST=..' .env &&
		grep 'DB_PORT=..' .env &&
		grep 'DB_DATABASE=..' .env &&
		grep 'DB_USERNAME=..' .env &&
		grep 'DB_PASSWORD=..' .env); then
		
		php artisan migrate || exit 32
	else
		echoRed 'Error: You have to check your .env file'
		exit 33
	fi
fi

# 打印自动加载索引
composer dump-autoload || exit 34

# 编译资源文件
if (find node_modules -name '*laravel-mix*' | grep 'laravel-mix' &> /dev/null); then
	npm run dev || exit 35
else
	echoRed 'Error: You have to install laravel-mix'
	exit 36
fi

# 环境配置
for aliyun in 'ALIYUN_ACCESS_KEY_ID' \
			  'ALIYUN_ACCESS_KEY_SECRET' \
			  'ALIYUN_MNS_ENDPOINT' \
			  'ALIYUN_MNS_TOPIC_NAME' \
			  'ALIYUN_MNS_SIGN_NAME' \
			  'ALIYUN_MNS_TEMPLATE_CODE' \
			  'ALIYUN_MNS_TEMPLATE_PRODUCT' \
			  'ALIYUN_MNS_TEMPLATE_CUSTOMER' \
			  'ALIYUN_MNS_TEMPLATE_ITEM' \
			  'ALIYUN_SEND_ADDRESS' \
			  'ALIYUN_SENDER' \
			  'ALIYUN_MAIL_TAG'
do
	grep $aliyun .env &> /dev/null || echo "$aliyun=" >> .env || exit 37
done

# 配置 Entrust
grep "'Quefei\\\\Myentrust\\\\Models\\\\Role'" config/entrust.php &> /dev/null || sed -i "s/'App\\\\Role'/'Quefei\\\\Myentrust\\\\Models\\\\Role'/g" config/entrust.php || exit 38
grep "'Quefei\\\\Myentrust\\\\Models\\\\Permission'" config/entrust.php &> /dev/null || sed -i "s/'App\\\\Permission'/'Quefei\\\\Myentrust\\\\Models\\\\Permission'/g" config/entrust.php || exit 39

# 配置 Searchy
grep "'ufuzzy', *" config/searchy.php &> /dev/null || sed -i "s/'fuzzy',/'ufuzzy',/g" config/searchy.php || exit 40

# 清理缓存
php artisan config:clear || exit 41

# 初始化用户、角色、权限
php artisan db:seed --class=EntrustTableSeeder || exit 42

# 排除错误2
EntrustRoleTrait='vendor/zizaco/entrust/src/Entrust/Traits/EntrustRoleTrait.php'

grep "Config::get('auth.providers.users.model')," $EntrustRoleTrait &> /dev/null || sed -i \
"s/Config::get('auth.model'),/Config::get('auth.providers.users.model'),/g" $EntrustRoleTrait || exit 43

end=$(date "+%s"); time=$((end-start))
# 结束语
clear
echoGreen "Install and configure quefei core successfully"
echoGreen "Time used: $time seconds"
echo ""
echoGreen "Default user: admin"
echoGreen "User password: 123456"
echoGreen "Site Title: $title"
echoGreen "Site Logo: $logo"
echoGreen "Site Copyright: $copyright"

